version: '3.7'

services:
  db:
    image: postgres
    env_file: ../.env
    ports:
      - "5432:5432"
  web:
    build: ../..
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: ../.env

volumes:
  db:
    driver: local



