# Generated by Django 4.2.1 on 2023-05-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_api', '0003_alter_user_friendlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friendList',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
